/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package flowlayoutframe;
import java.awt.FlowLayout;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JButton;
/**
 *
 * @author bageg
 */
 /*
    Algo 
    1) initalize Buttons and container and flowlayout
    2) In constructor give title with suoer
    3) declare flowlayout and containfer in a variable for container = getContentPane
    4) set Layout
    5) declare button and give name
    6) add button
    7) button.addActionListener
    8) make anonymous inner class 
    9) override and make function actionPerformed
    10) setAligment to ur choice
    11) realign attached components layout.layoutContainer(container);
    */
public class NewJFrame extends JFrame implements ActionListener {

    /**
     * Creates new form NewJFrame
     */
    private final JButton leftJButton;
    private final JButton centerJButton;
    private final JButton rightJButton;
    private final FlowLayout layout;
//    private final Container container;
    
   
    public NewJFrame() {
        super("FlowLayout Demo");
        layout = new FlowLayout();
//        container = getContentPane();
        setLayout(layout);
        
        leftJButton = new JButton("Left");
        leftJButton.addActionListener(this);
        add(leftJButton);
//        leftJButton.addActionListener(
//                new ActionListener(){
//                    @Override
//                    public void actionPerformed(ActionEvent event){
//                        layout.setAlignment(FlowLayout.LEFT);
//                        layout.layoutContainer(container);
//                    }
//        
//                }
//        );
        
        centerJButton = new JButton("Center");
        centerJButton.addActionListener(this);
        add(centerJButton);
//        centerJButton.addActionListener(
//                new ActionListener(){
//                    @Override
//                    public void actionPerformed(ActionEvent event){
//                        layout.setAlignment(FlowLayout.CENTER);
//                        layout.layoutContainer(container);
//                    }
//                }
//        );
        rightJButton = new JButton("right");
        rightJButton.addActionListener(this);
        add(rightJButton);
//        rightJButton.addActionListener(
//                new ActionListener(){
//                    @Override
//                    public void actionPerformed(ActionEvent event){
//                        layout.setAlignment(FlowLayout.RIGHT);
//                        layout.layoutContainer(container);
//                    }
//                }
//        );
//        
        
//        initComponents();
    }
    @Override
    public void actionPerformed(ActionEvent event){
        if( event.getSource() == rightJButton){
            layout.setAlignment(FlowLayout.RIGHT);
            layout.layoutContainer(getContentPane());
        }
        if(event.getSource() == leftJButton){
            layout.setAlignment(FlowLayout.LEFT);
            layout.layoutContainer(getContentPane());
        }
        if (event.getSource() == centerJButton ){
            layout.setAlignment(FlowLayout.CENTER);
            layout.layoutContainer(getContentPane());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
/**/